development:
  adapter: postgresql
  encoding: unicode
  database: sandbox
  pool: 5
  username: andius
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: sandbox_test
  pool: 5
  username: andius
  password: domgeo
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: sandbox
  pool: 5
  username: andius
  password:
  min_messages: warning
